
services:
    web:
        build: .
        volumes:
            - type: bind
              source: .
              target: /opt/app/
        ports:
            - 5000:5000
        entrypoint:
            - uvicorn
            - --port
            - "5000"
            - --host
            - "0.0.0.0"
            - wsgi:app
        env_file: 
            - file.env
        networks:
            - web_network

networks:
    web_network: