
services:
    web:
        build: .
        ports:
            - 5000:5000
        entrypoint: 
            - gunicorn
            - -b
            - "0.0.0.0:5000"
            - -w
            - "1"
            - -k
            - "uvicorn.workers.UvicornWorker"
            - wsgi:app
        env_file: 
            - file.env
        networks:
            - web_network

networks:
    web_network: